time_window: 5  # 时间窗口大小(秒)


# 数据配置
data:
  log_path: "/home/fuxian/DataSet/NewDataset/ob/2022-08-22/log/log.csv"
  trace_path: "/home/fuxian/DataSet/NewDataset/ob/2022-08-22/trace/trace.csv"
  metric_path: "/home/fuxian/DataSet/NewDataset/ob/2022-08-22/metric/"
  timestamp_format: "unix"  # 添加时间戳格式配置
  # date_column: "timestamp"  # 指定时间戳列名
  metric_types:
    - cpuusage
    - memoryusage
    - latencyp50
    - latencyp90
    - latencyp95
    - latencyp99
    - networkreceivebytes
    - networktransmitbytes
    - successrate
  
# 特征提取配置
feature:
  log_template_size: 2000  # 日志模板数量上限
  trace_latency_threshold: 1000  # 追踪延迟阈值(ms)

# VAE模型配置  
feature_size: 40  # 特征维度（不包含 window 列）
vae:
  hidden_size: 128
  latent_size: 32
  learning_rate: 0.001
  batch_size: 64
  epochs: 100
  reconstruction_threshold: 0.7 # 重建概率阈值

# 因果分析配置
causal:
  time_window: 300  # 因果分析时间窗口(秒)
  significance_level: 0.05  # 显著性水平
  max_lag: 5  # 最大滞后阶数

# 强化学习配置
rl:
  learning_rate: 0.01
  discount_factor: 0.9
  epsilon: 0.1

# 添加服务列表配置
services:
  - adservice-5f6585d649-fnmft
  - cartservice-579f59597d-wc2lz
  - checkoutservice-578fcf4766-9csqn
  - currencyservice-cf787dd48-vpjrd
  - emailservice-55fdc5b988-f6xth
  - frontend-579b9bff58-t2dbm
  - paymentservice-9cdb6588f-554sm
  - productcatalogservice-668d5f85fb-wckp8
  - recommendationservice-6cfdd55578-gfj6q
  - shippingservice-7b598fc7d-lmggd


# 评估指标配置
evaluation:
  metrics:
    - precision
    - recall
    - f1_score
  ground_truth_path: "/home/fuxian/DataSet/NewDataset/ob/2022-08-22/groundtruth.csv"